### ISSUE TITLE
Hiding the modifiers, but not health

### ISSUE THREAD

**Issue by ByteAlex** [ReadieFur/BSDP-Overlay#11]
I personally rarely play with modifiers and it'd just be sitting on my overlay for no reason, though I think the health bar would be interesting.
But I'd love to get more positioning options for the health bar.
For example right under the stats.

**Comment by kOFReadie** [comment]
> I personally rarely play with modifiers and it'd just be sitting on my overlay for no reason, though I think the health bar would be interesting.
> But I'd love to get more positioning options for the health bar.
> For example right under the stats.

Dont know why it took me so long to see this.
If you would like you can request access to my early access [overlay editor](https://github.com/kOFReadie/BSDP-Overlay/tree/closed-beta)
That might come out pubically soon as ive not really had any feedback.

**Comment by ByteAlex** [comment]
Hello @kOFReadie,
thanks for your update. I'd love to test it out. Where can I request access?

**Comment by kOFReadie** [comment]
> Hello @kOFReadie,
> thanks for your update. I'd love to test it out. Where can I request access?

If you message me on discord I can yun you down on it and get you set up.
Readie#6594
